name: Build and deploy Node.js app to Azure Web App - WeatherNodesInitiative

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip Release
        run: |
          zip -r release.zip build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: release-zip

      - name: List files after downloading artifact
        run: ls -al

      - name: Unzip artifact for deployment
        run: unzip release.zip -d $HOME/site/wwwroot

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F30C81DBEAE41D2A80C1B83E6BA5D05 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D92CC9ACAEF49E1A028A05ACC7156A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_792C41D5FDE945E7A32E791B2199AC7D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WeatherNodesInitiative'
          slot-name: 'Production'
          package: $HOME/site/wwwroot/release.zip
