name: Build and deploy Node.js app to Azure Web App - WeatherNodesInitiative

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.14"

      - name: install, cross-env, build testing
        run: |
          npm install
          npm install cross-env --save-dev
          npm run build

      - name: List files in build directory for verification
        run: ls -la build

      - name: Compress build directory
        run: zip -r build.zip build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip build artifact
        run: unzip build.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F30C81DBEAE41D2A80C1B83E6BA5D05}}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D92CC9ACAEF49E1A028A05ACC7156A6}}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_792C41D5FDE945E7A32E791B2199AC7D}}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "WeatherNodesInitiative"
          slot-name: "Production"
          package: ./build
