name: Build and deploy Node.js app to Azure Web App - WeatherNodesInitiative

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install cross-env
        run: npm install cross-env --save-dev

      - name: Build the project
        run: npm run build

      - name: Zip the build folder
        run: zip -r release.zip build/

      - name: List files after zip creation
        run: ls -al

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: release.zip

      - name: List files after downloading artifact
        run: ls -al

      - name: Verify content of the release.zip
        run: unzip -l release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F30C81DBEAE41D2A80C1B83E6BA5D05 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D92CC9ACAEF49E1A028A05ACC7156A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_792C41D5FDE945E7A32E791B2199AC7D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WeatherNodesInitiative'
          slot-name: 'Production'
          package: release.zip
